#pragma once

#include "SDL_events.h"

#define SIZE 82

typedef enum 
{
	SCANCODE_UNKNOWN = 0,

	SCANCODE_A = 4,
	SCANCODE_B = 5,
	SCANCODE_C = 6,
	SCANCODE_D = 7,
	SCANCODE_E = 8,
	SCANCODE_F = 9,
	SCANCODE_G = 10,
	SCANCODE_H = 11,
	SCANCODE_I = 12,
	SCANCODE_J = 13,
	SCANCODE_K = 14,
	SCANCODE_L = 15,
	SCANCODE_M = 16,
	SCANCODE_N = 17,
	SCANCODE_O = 18,
	SCANCODE_P = 19,
	SCANCODE_Q = 20,
	SCANCODE_R = 21,
	SCANCODE_S = 22,
	SCANCODE_T = 23,
	SCANCODE_U = 24,
	SCANCODE_V = 25,
	SCANCODE_W = 26,
	SCANCODE_X = 27,
	SCANCODE_Y = 28,
	SCANCODE_Z = 29,

	SCANCODE_1 = 30,
	SCANCODE_2 = 31,
	SCANCODE_3 = 32,
	SCANCODE_4 = 33,
	SCANCODE_5 = 34,
	SCANCODE_6 = 35,
	SCANCODE_7 = 36,
	SCANCODE_8 = 37,
	SCANCODE_9 = 38,
	SCANCODE_0 = 39,

	SCANCODE_RETURN = 40,
	SCANCODE_ESCAPE = 41,
	SCANCODE_BACKSPACE = 42,
	SCANCODE_TAB = 43,
	SCANCODE_SPACE = 44,

	SCANCODE_RIGHT = 79,
	SCANCODE_LEFT = 80,
	SCANCODE_DOWN = 81,
	SCANCODE_UP = 82

} ScancodeKey;

typedef enum
{
	MOUSE_LEFT,
	MOUSE_RIGHT,

	//Limite de raton
	MOUSE_MAX
} MouseButton; 